# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
name: servicesmongo # application name
# registry: exampleuser # dockerhub username or container registry hostname

ingress:
  - name: ingress
    bindings:
      - port: 5000
    rules:
      - path: /userapi
        service: user
      - path: /productapi
        service: product

# define multiple services here
services:
  # - name: gateway
  #   project: ./gateway/gateway.csproj
  #   bindings:
  #     - port: 5000
  - name: user
    project: ./userservice/userservice.csproj
    bindings:
      - port: 5001
  - name: product
    project: ./productservice/productservice.csproj
    bindings:
      - port: 5002
  - name: mongo1
    image: mongo:4.2.6
    args: "--port 27018"
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: 123456
    bindings:
      - port: 27018
        connectionString: "mongodb://root:123456@${host}:${port}"
  - name: mongo2
    image: mongo:4.2.6
    args: "--port 27019"
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: 123456
    bindings:
      - port: 27019
        connectionString: "mongodb://root:123456@${host}:${port}"
    # project: app.csproj # msbuild project path (relative to this file)
    # executable: app.exe # path to an executable (relative to this file)
    # args: --arg1=3 # arguments to pass to the process
    # replicas: 5 # number of times to launch the application
    # env: # array of environment variables
    #  - name: key
    #    value: value
    # bindings: # optional array of bindings (ports, connection strings)
    # - port: 8080 # number port of the binding
